// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjdjpfKrkKjtlAL3tJDcyfrDouWBbuoIU',
    appId: '1:17192129681:android:786491dd9bcae9d9651b30',
    messagingSenderId: '17192129681',
    projectId: 'flutter-quiz-1893b',
    databaseURL: 'https://flutter-quiz-1893b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-quiz-1893b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC502_HIaAGnAZ7V3CSG4JfVgL5i-aOLbk',
    appId: '1:17192129681:ios:1b74cb9e8fc97164651b30',
    messagingSenderId: '17192129681',
    projectId: 'flutter-quiz-1893b',
    databaseURL: 'https://flutter-quiz-1893b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-quiz-1893b.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

}